language: python
python:
  - '3.5'

env:
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost

services:
  - postgresql

install:
  - pip3 install -r ./requirements.txt

before_script:
  - psql -U postgres -c 'create database "test_shivadb";'
  - psql -U postgres -c 'create user "shivauser" with password "1";'
  - psql -U postgres -c 'alter role shivauser with superuser;'

script: python3 ./manage.py test --no-input
