sudo: required

language: python
python:
  - '3.5'
cache: pip

env:
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost
  - SHIVA_DB_PORT=5433

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

services:
  - postgresql
  - rabbitmq

install:
  - pip3 install -r ./requirements.txt

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c "create user shivauser with password '1';"
  - psql -U postgres -c "alter role shivauser with superuser;"
  - sudo rabbitmqctl add_user shivauser 1
  - sudo rabbitmqctl add_vhost shivahost
  - sudo rabbitmqctl set_user_tags shivauser shivatag
  - sudo rabbitmqctl set_permissions -p shivahost shivauser ".*" ".*" ".*"
  - mkdir -p $HOME/shiva/log/celery
  - mkdir -p $HOME/shiva/run/celery

script:
  - flake8 --exit-zero --exclude=migrations .
  - celery multi start worker --logfile="$HOME/shiva/log/celery/%N.log" --pidfile="$HOME/shiva/run/celery/%N.pid"
  - coverage run --include=./* ./manage.py test --no-input

after_success:
  - coverage report
  - coveralls