# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('visit_time', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Person')),
            ],
        ),
    ]
