# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.TextField(db_index=True)),
                ('info_value', models.TextField(db_index=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='personinfo',
            unique_together=set([('person', 'info_type', 'info_value')]),
        ),
    ]
