# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160706_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('action_type', models.IntegerField(choices=[(0, 'Backend trigger'), (1, 'Frontend trigger')])),
            ],
        ),
    ]
