# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('event_value', models.TextField(blank=True, default='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Person')),
            ],
        ),
    ]
