# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 04:35
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_personevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personvisit',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 4, 34, 41, 618551, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 4, 34, 46, 595789, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='personvisit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 4, 34, 59, 770949, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 4, 35, 3, 986938, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
