# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160711_0435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonInfo',
            new_name='PersonContact',
        ),
    ]
