# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160711_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.TextField(db_index=True)),
                ('data_value', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='persondata',
            unique_together=set([('person', 'data_type', 'data_value')]),
        ),
    ]
