# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20160711_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
