# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 18:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20160713_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
